// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mprnuaxcjxauvmfaxgvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wcm51YXhjanhhdXZtZmF4Z3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTQ1OTEsImV4cCI6MjA2Njg5MDU5MX0.Jv50RSSy-np32SaeOz0Uw65hdG1VLT_VTzVv1ZMyK-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});